### ISSUE TITLE
Any plans to update to current version?

### ISSUE THREAD

**Issue by dibok** [dliw/fpCEF3#79] opened 2020-03-26 20:44 UTC
Hi
Master branch has support for version 3.3029, in development branch is support 3.3538, that is still 3 years old (current versions are 80.X). Problem is that CEF build packages for 3.X doesn't contain libwidevine binaries which are required for DRM websites (new CEF builds have them). Seems that libwidevine has to be for specific CEF version and it is hard to find such old ones.
Is fpCEF3 still maintained?

Regards

**Comment by dliw** [comment] 2020-03-26 21:35
Duplicate of #77.

**Closed as completed by dliw** 2020-03-26 21:35 UTC
